[package]
name = "bizzle"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
rand = "0.8.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
num-format = "0.4"

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["json"]